### ISSUE TITLE
lambda-simple-deploy doesn't exist in npm registry

### ISSUE THREAD

**Issue by felquis** [pagarme/lambda-simple-deploy#9]
I tried to use the commands in the readme, but it does't work because there's no such module in npm registry

I think we should: 

1 - Publish it
2 - Write how to run it locally?

Best

**Comment by mccraveiro** [comment]
This project was deprecated in favor of https://github.com/pagarme/deployer
@grvcoelho should we delete this repo?

**Comment by grvcoelho** [comment]
@mccraveiro I'm against deleting things as they provide historical value. Maybe we should put a deprecated warning somewhere here :) what do you think?
